### ISSUE TITLE
strange rounding in legend

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.leaflet.js#11]
seems to have rounded all of the bounds except for one

![image](https://cloud.githubusercontent.com/assets/1366709/10615273/ece829d0-772c-11e5-8465-e974bb2662a4.png)

**Comment by KatiRG** [comment]
What input data are you using? I can try to reproduce it.

**Comment by KatiRG** [comment]
For some reason, I am getting this error in the console after pulling the master branch:

ReferenceError: tip is not defined
chart.selectAll("path").call(tip);

**Comment by gordonwoodhull** [comment]
I'm testing it from an R package, so I'm not sure how to reproduce it in pure JS. 

The `.tip` error is just some test code I accidentally checked in - I'll remove it today.

**Comment by gordonwoodhull** [comment]
It was just that `grade[0]` wasn't rounded, while the rest were:

``` js
        grades[0] = Math.round(minValue);
```

I think this legend code could use to be generalized for cases like where the color scale is not equally divided, or where the grades are not integers, but we can deal with that as we go along. Thanks!
