### ISSUE TITLE
The popup in Choropleth doesn't work

### ISSUE THREAD

**Issue by ackuser** [dc-js/dc.leaflet.js#22]
In dc.leaflet version 0.2.3 for the Choropleth Chart  the popup doesn't work or it doesn't get rendered. Am I wrong or it happens to anybody else? I will be happy to fix that but I would need some help.

``` javascript
      .renderPopup(true)
      .popup(function(d,feature) {
        return feature.properties.name+" : "+d.value;
      });
```

Anyway, any help would be really appreciated

**Comment by msimonin** [comment]
Hi @ackuser,

The same here !

**Comment by gordonwoodhull** [comment]
Doesn't appear to work for the marker chart either. It looks like it's set up correctly but I don't know, maybe the clicks are getting through or something.

**Comment by msimonin** [comment]
![image](https://user-images.githubusercontent.com/2486813/81299743-f63db000-9076-11ea-8c4f-ab5080075841.png)
Popups seem ok with ClusterMarkers

**Comment by msimonin** [comment]
Ok I made a quick test: setting `brushOn(false)` on the chart makes the popup appears.
Setting both `onClick` event and the `bindPopup` on the layers seems to an issue (leaflet issue ?)

**Comment by gordonwoodhull** [comment]
Thanks for testing. I dug into it a little more, and it looks like the event handling is fine, but the issue is that `brushOn` will cause filtering, which causes a redraw of the map. Redrawing erases the popup.

On the [demo page](http://dc-js.github.io/dc.leaflet.js/), it looks like there is a similar issue with the cluster marker: clicking a cluster causes zooming, which erases the popup. The popup works on a non-cluster (fully expanded) marker.

Do you want to filter and show the popup at the same time?

**Comment by gordonwoodhull** [comment]
I haven't looked into how to implement this, but I suppose one or the other action could be triggered only when a modifier key is pressed.

**Comment by msimonin** [comment]
Hi @gordonwoodhull ,
That would be great to trigger one or another action with a modifier key :) 
In the time being wouldn't it be possible to bind a key event on the markers to show the popup and keep the click event for the filtering as it is ?

**Comment by gordonwoodhull** [comment]
I don’t understand the distinction. Either way you are enabling or disabling one of the actions based on what keys are pressed, right?

**Comment by gordonwoodhull** [comment]
Okay, I implemented `.popupMod()` and `.filterMod()` for the marker chart and choropleth in version 0.5.1.

@msimonin, please check if [the documentation on LeafletBase](https://github.com/dc-js/dc.leaflet.js#leaflet-base) is sufficient, and leave a comment here if it needs more explanation or doesn't work.

I changed the demo to display popups only when the control key (command key on Macs) is pressed.

**Comment by msimonin** [comment]
I just tested and it's perfect !
Thanks a lot @gordonwoodhull :)
