### ISSUE TITLE
Upgrading leaflet versions

### ISSUE THREAD

**Issue by doshisunny** [dc-js/dc.leaflet.js#24]
Is it possible to update leaflet version to 1.0.2 and leaflet.markercluster to 1.0.0 ?
These are the latest versions of leaflet. 
I am planning use in new app and just wanted to start with newer versions.

**Comment by gordonwoodhull** [comment]
Hi @doshisunny, that's a great idea. Are you willing to try it yourself and report what errors you run into?

**Comment by doshisunny** [comment]
Thanks, @gordonwoodhull 
I will update versions and test will our app. I will make a merge request after that. I will let you know if I find any issues.

**Comment by rrameshkumar76** [comment]
I was also looking at this with sunny, The examples were using web/js for dependencies.
I updated the leaflet version and made changes for the example to use the node modules js files and dc.leaflet.js file in root.
I did not find any issues or errors in console using just the example provided and have made a pull request.

**Comment by gordonwoodhull** [comment]
Released in 0.3.1
