### ISSUE TITLE
.marker(function(d, map) {}): map is undefined

### ISSUE THREAD

**Issue by DienNM** [dc-js/dc.leaflet.js#30]
Hi,
I am using .marker to customize something. I follow the document but "map" is undefined. d: is correct.
Thanks,
Dien

**Comment by gordonwoodhull** [comment]
I'm not sure how useful this is, given that the `map` is the same as `markerChart.map()`, but I agree that the library should follow its documentation!

Fixing this for 0.3.2.

**Comment by gordonwoodhull** [comment]
Thanks @DienNM!

**Comment by DienNM** [comment]
Thanks @gordonwoodhull
