### ISSUE TITLE
not compatible with dc.js 4.0

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.leaflet.js#39]
dc.leaflet.js still uses the dc.js 1.0 `baseChart`, which was changed to `baseMixin` in 2.0 and [removed in 4.0](https://github.com/dc-js/dc.js/blob/develop/docs/dc-v4-upgrade-guide.md).

**Comment by msalemwhyise** [comment]
+1 .. been fighting with this issue for the past 2 days to no use.
Waiting for a response from the team!

**Comment by gordonwoodhull** [comment]
Hi @msalemwhyise! Please report issues when you run into them. I only discovered this because I was answering a question on SO.

I’ll try to push out a fix today.

**Comment by gordonwoodhull** [comment]
Released as 0.5.0. 

Thanks for the nudge, @msalemwhyise. It was interesting to get this working, and I'm documenting what I learned in the [dc@4 upgrade guide](https://github.com/dc-js/dc.js/blob/develop/docs/dc-v4-upgrade-guide.md#steps-to-upgrade).
