### ISSUE TITLE
Reset all 

### ISSUE THREAD

**Issue by Tablel352** [dc-js/dc.leaflet.js#42]
When executing a "reset all"..

`<a href="javascript:dc.renderAll(); dc.redrawAll()">Reset all</a>`

.. the layer of circles on a bubbleChart get stacked on top of each other.

It seems like the old layer first has to be removed.

**Comment by gordonwoodhull** [comment]
Normally you would do

```js
dc.filterAll(); dc.redrawAll();
```

I.e. there is no need to re-render to implement "reset all". If you really need to re-render for some reason, you are right that it doesn't clear the chart - that's issue #15.
