### ISSUE TITLE
gray-out colors?

### ISSUE THREAD

**Issue by Tablel352** [dc-js/dc.leaflet.js#43]
In the dc charts (not dc leaflet), when selecting a group, the other groups get grayed-out. (tested with the bubbleChart)

Would this also be desired behavior for the dc leaflet maps?

**Comment by gordonwoodhull** [comment]
As mentioned in [the documentation](https://github.com/dc-js/dc.leaflet.js), you can set the `unselectedColor` to a function. The chart takes this somewhat literally, and will show all bubbles that color even when none is selected. To approximate the behavior of other charts, you can do 

```js
          .unselectedColor(d => choro.filters().length ? 'grey' : choro.getColor(d))
```
Only single selection is supported, though.

<img width="256" alt="image" src="https://user-images.githubusercontent.com/1366709/123963928-ec64c380-d980-11eb-94c5-721474b8c88e.png">

**Comment by Tablel352** [comment]
thanks, works now!
