### ISSUE TITLE
Broken demo

### ISSUE THREAD

**Issue by tayden** [dc-js/dc.leaflet.js#5]
The demo doesn't render the maps properly and is complaining about the deprecated renderlet method. I'm also having trouble with getting the maps to render. Is the library working with dc 2.0.0-beta.19? 

Edit: It seems that the problem is with width being properly set on the div.dc-leaflet.leaflet-container element and its child divs

**Comment by gordonwoodhull** [comment]
Thanks for the report! It should be working, will take a look.

**Comment by tayden** [comment]
I've figured this out I reckon. Working on a pull request.
